### PR TITLE
remove ImageUtils dependency

### PR DESCRIPTION
**Pull request by Laura2305**

### CODE REVIEW

**Comment by alexjaffray** [comment]
@Laura2305 This is a good move if we don't need it for anything. I'll review once CI passes

**Comment by Laura2305** [comment]
@alexjaffray CompatHelper fails and there is a version conflict between Images and ImageUtils, so I've tried to use Images only and delete the ImageUtils dependency. I hope it works. I'm sorry I've been taking some time, I have been busy.

**Comment by alexjaffray** [comment]
> @alexjaffray CompatHelper fails and there is a version conflict between Images and ImageUtils, so I've tried to use Images only and delete the ImageUtils dependency. I hope it works. I'm sorry I've been taking some time, I have been busy.

@Laura2305 No worries, there's no rush from my side. The package is registered and the tests pass on the registrator CI, so I don't think it's a major issue.

**Review by alexjaffray — APPROVED** [review]

**Comment by alexjaffray** [comment]
@Laura2305 CI passed, merged

**Pull request merged**
