### PR TITLE
Fix compat helper

### PR DESCRIPTION
**Pull request by Laura2305**

### CODE REVIEW

**Comment by Laura2305** [comment]
Hi @alexjaffray, This is ready to be reviewed and merged.

**Review by alexjaffray — COMMENTED** [review]
Do you have a hypothesis for why the tolerance on the uniformity correction check got larger? @Laura2305

**Comment by Laura2305** [comment]
It has always been occasionally failing, as the tolerance was quite low. I usually solved that re-running the tests, but this seems like a better solution.

**Review by alexjaffray — APPROVED** [review]
The changes make sense to improve reliable testing, I see no problem with increasing the tolerance for the test. Approved.

**Comment by Laura2305** [comment]
@alexjaffray thanks! Merging now.

**Pull request merged**
