### PR TITLE
Update Project.toml

### PR DESCRIPTION
**Pull request by Laura2305**

### CODE REVIEW

**Comment by alexjaffray** [comment]
@Laura2305 do you know why the tests are failing?

**Comment by Laura2305** [comment]
@alexjaffray there's a problem with the connected components algorithm in v0.26 of Images.jl. I'm looking into it.

**Comment by Laura2305** [comment]
@alexjaffray fixed :)

**Comment by alexjaffray** [comment]
Thanks! Merging

**Review by alexjaffray — APPROVED** [review]

**Pull request merged**
